import enum
import math

MATCHING_WEIGHTS_LIMITS = (1, 100)

NUM_LEFT = 10
NUM_RIGHT = 10

NUM_RUNS = 5
NUM_AGENTS = NUM_LEFT

PROPORTION_OF_EDGES_PER_SUBGRAPH = 1 / 3

CONNECTIVITY_GRAPH_EDGE_PROPORTION = 1 / math.sqrt(NUM_AGENTS)

DISCREPANCY_THRESHOLD = 0.25 * min(NUM_RIGHT, NUM_LEFT)

MIN_ALLOWED_MATCHING_SCORE_PROPORTION = 0.6


class Difficulty(enum.IntEnum):
    EASY = NUM_AGENTS ** 3
    MEDIUM = NUM_AGENTS ** 2
    HARD = NUM_AGENTS * 2
